### ISSUE TITLE
protoc命令生成的pb文件缺少  common.ErrorWithAttachment

### ISSUE THREAD

**Issue by wwek** [dubbogo/tools#16]
安装和生成pb
```
export GO111MODULE="on"
export GOPROXY="http://goproxy.io"
go install github.com/dubbogo/tools/cmd/protoc-gen-triple
cd api
protoc -I . helloworld.proto --triple_out=plugins=triple:.
```
结果：

![image](https://user-images.githubusercontent.com/1239403/139380663-2f262377-dc1b-4bf1-a8ca-53e15f144b32.png)

环境信息：
	dubbo.apache.org/dubbo-go/v3 v3.0.0-rc2
	github.com/dubbogo/triple v1.0.1

**Comment by LaurenceLiZhixin** [comment]
@wwek Please refer to newest doc: at https://dubbogo.github.io , you can join dingtalk group 23331795 to discuss we us.
