### ISSUE TITLE
support multi pb for dubbo3grpc

### ISSUE THREAD

**Issue by lethexixin** [dubbogo/tools#18]
之前在dubbo-go里评论过这个问题: 
https://github.com/apache/dubbo-go/pull/1261#issuecomment-889575887
![image](https://user-images.githubusercontent.com/46220496/139779735-4bdb8dc3-4552-4626-8161-9ee5737d8fd1.png)

一开始在这个pull中修复了这个问题, 
https://github.com/apache/dubbo-go/pull/1361

但是现在 https://github.com/dubbogo/tools/tree/master/cmd/protoc-gen-dubbo3grpc 中仍然还是存在这个问题, 能否修复下

**Comment by LaurenceLiZhixin** [comment]
请加入钉钉群23331795沟通一下 @lethexixin

**Comment by jasondeng1997** [comment]
OK
